export const CHEERS_BROADCAST = 'CHEERS_BROADCAST';
export const CLOSEUP_ON = 'CLOSEUP_ON';
export const CLOSEUP_OFF = 'CLOSEUP_OFF';
export const CLOSEUP_BREAK = 'CLOSEUP_BREAK';

export const UPDOWN_START = 'UPDOWN_START';
export const LIAR_START = 'LIAR_START';
export const RANDOM_PICK_START = 'RANDOM_PICK_START';
export const GAME_STOP = 'GAME_STOP';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';

export const STREAM_CHANGE_VIDEO = 'STREAM_CHANGE_VIDEO';
export const STREAM_CHANGE_AUDIO = 'STREAM_CHANGE_AUDIO';
export const STREAM_FORCE_CHANGE_VIDEO = 'STREAM_FORCE_CHANGE_VIDEO';
export const STREAM_FORCE_CHANGE_AUDIO = 'STREAM_FORCE_CHANGE_AUDIO';

export const CHAT_RECEIVE = 'CHAT_RECEIVE';
export const CHAT_SENDING = 'CHAT_SENDING';

export const MARK_BROADCAST = 'MARK_BROADCAST';

export const FRIEND_REQUEST = 'FRIEND_REQUEST';

export const CONTROL_AUTHORITY_ERROR = 'CONTROL_AUTHORITY_ERROR';
export const CONTROL_TOGGLE_ENTRY = 'CONTROL_TOGGLE_ENTRY';
export const CONTROL_OTHER_VIDEO_OFF = 'CONTROL_OTHER_VIDEO_OFF';
export const CONTROL_OTHER_AUDIO_OFF = 'CONTROL_OTHER_AUDIO_OFF';

export const TICKET_REQUEST = 'TICKET_REQUEST';
export const TICKET_SUCCESS = 'TICKET_SUCCESS';
export const TICKET_FAILURE = 'TICKET_FAILURE';

export const ENTER_ROOM = 'ENTER_ROOM';
export const ENTER_ROOM_ERROR = 'ENTER_ROOM_ERROR';
export const ENTER_ALL_USER = 'ENTER_ALL_USER';
export const ENTER_ONE_USER = 'ENTER_ONE_USER';
export const ENTER_CHANGE_HOST = 'ENTER_CHANGE_HOST';
export const DISCONNECT_USER = 'DISCONNECT_USER';

export const VOTE_START = 'VOTE_START';
export const VOTE_DECISION = 'VOTE_DECISION';
export const VOTE_GET_DECISION = 'VOTE_GET_DECISION';
export const VOTE_JUDGE_ON = 'VOTE_JUDGE_ON';
export const VOTE_JUDGE_OFF = 'VOTE_JUDGE_OFF';
export const VOTE_PRISON_BREAK = 'VOTE_PRISON_BREAK';

export const SIGNAL_NEED_OFFERS = 'SIGNAL_NEED_OFFERS';
export const SIGNAL_OFFER = 'SIGNAL_OFFER';
export const SIGNAL_ANSWER = 'SIGNAL_ANSWER';
export const SIGNAL_ICE = 'SIGNAL_ICE';
